FROM python:3.12-alpine3.21
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip -r requirements.txt
COPY requirements-test.txt .
RUN pip install --no-cache-dir --upgrade pip -r requirements-test.txt
COPY ./app /app
COPY ./tests /tests

WORKDIR /

ENTRYPOINT ["pytest", "/tests","-v"]