services:
  db:
    image: postgres:16.6-alpine3.21
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
        - db
    env_file:
      - .env